language: python

dist: trusty

services:
  - docker

before_install:
- docker pull mysql:5.7
- mkdir -p ~/cs4501/db
- docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql mysql:5.7
- sleep 20
- docker run --name mysql-cmdline --link mysql:db -d -e MYSQL_ROOT_PASSWORD='$3cureUS' mysql:5.7 
- sleep 20
- docker exec -i mysql-cmdline mysql -h db -P 3306 -uroot -p'$3cureUS' <<< "create user 'www'@'%' identified by '$3cureUS';create database cs4501 character set utf8;grant all on *.* to 'www'@'%';\q" 
- sleep 10
- docker-compose up -d
- docker network connect isa_backend mysql
- sleep 10

script:
- docker exec models python manage.py test
