language: python

dist: trusty

services:
  - docker

before_script:
- chmod +x setup.sh
- ./setup.sh

script:
- docker ps
- docker-compose up -d
- docker network connect isa_backend mysql
- docker-compose stop
- docker-compose up -d
- docker exec models bash -c "python manage.py test"
