language: python

services:
  - docker

before_install:
- docker pull tp33/django
- docker pull spotify/kafka
- docker pull elasticsearch:7.4.0
- docker pull mysql:latest
- mkdir -p ~/cs4501/db
- docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/cs4501/app:/app mysql:latest
- docker ps
- docker exec -i mysql mysql -uroot -p'$3cureUS' -Bse "create user 'www' identified with mysql_native_password by '$3cureUS';create database cs4501 character set utf8;grant all on cs4501.* to 'www';\q"

script:
- docker-compose up -d
- docker network connect isa_backend mysql
