language: python

services:
  - docker

before_install:
- docker pull tp33/django
- docker pull spotify/kafka
- docker pull elasticsearch:7.4.0
- docker pull mysql:latest

script:
- docker-compose up
