language: python

dist: trusty

services:
  - docker

before_script:
- chmod +x setup.sh
- ./setup.sh

script:
- docker ps
- docker-compose up -d
- docker network connect isa_backend mysql
- docker-compose down
- docker-compose up
- docker exec models python manage.py test
