language: python

services:
  - docker

before_install:
- docker pull tp33/django
- docker pull spotify/kafka
- docker pull elasticsearch:7.4.0
- docker pull mysql:latest
- mkdir -p ~/isa/db
- docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql mysql:latest
- chmod +x db_setup.sh
- docker run --name mysql-cmdline --link mysql:db mysql:latest
- docker exec -it mysql-cmdline /bin/bash -c " ./db_setup.sh"
- docker network connect isa_backend mysql
- docker-compose up -d

script:
- docker exec -it models bash
- python manage.py test
