language: python

services:
  - docker

before_install:
- docker pull tp33/django
- docker pull spotify/kafka
- docker pull elasticsearch:7.4.0
- docker pull mysql:5.7
- mkdir -p ~/cs4501/db
- docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql mysql:5.7
- docker run -i --name mysql-cmdline -d -e MYSQL_ROOT_PASSWORD='$3cureUS' --link mysql:db mysql:5.7 mysql -uroot -p'$3cureUS' -Bse "create user 'www' identified with mysql_native_password by '$3cureUS';create database cs4501 character set utf8;grant all on cs4501.* to 'www';\q"

script:
- docker-compose up -d
- docker-compose stop    
- docker network connect isa_backend mysql
- docker stop mysql
- docker start mysql
- docker ps
- sleep 10
- docker-compose up
