language: python

services:
  - docker

before_install:
- docker pull tp33/django
- docker pull spotify/kafka
- docker pull elasticsearch:7.4.0
- docker pull mysql:latest
- mkdir -p ~/isa/db
- docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/isa/db:/var/lib/mysql mysql:latest
- docker run -i --name mysql-cmdline -d -e MYSQL_ROOT_PASSWORD='$3cureUS' --link mysql:db mysql:latest mysql -uroot -p'$3cureUS' -Bse "create user 'www'@'%' identified with mysql_native_password by '$3cureUS';create database cs4501 character set utf8;grant all on cs4501.* to 'www'@'%';quit":
- exit
- docker network connect isa_backend mysql
- docker-compose up -d

script:
- docker exec -it models bash
- python manage.py test
