version: "3"
services:
  models:
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - ./egg:/app
    ports:
      - "8001:8000"
    networks:
      - backend
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && mod_wsgi-express start-server --working-directory ./ --reload-on-changes ./egg/wsgi.py"

networks:
  backend: