version: "3"
services:
  # haproxy:
  #   image: isa-haproxy
  #   container_name: haproxy
  #   ports:
  #     - 80:80
  #   networks:
  #     - public
  #     - service_mesh
    
  models:
    image: tp33/django
    container_name: models
    # logging:
    #   driver: "none"
    environment: 
      - TRAVIS
    external_links:
      - mysql:db
    volumes:
      - ./models:/app
    ports:
      - "8001:8000"
    networks:
      - service_mesh
      - backend
    command: bash -c "pip install whitenoise
      && pip install django-crispy-forms
      && pip install boto3
      && pip install django-storages
      && pip install selenium
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py loaddata ./fixtures/manufacturer_fixtures.json
      && python manage.py loaddata ./fixtures/product_fixtures.json
      && mod_wsgi-express start-server --reload-on-changes ./models/wsgi.py"

  services:
    image: tp33/django
    container_name: services
    # logging:
    #   driver: "none"
    networks:
      - service_mesh
      - public
    ports:
      - "8002:8000"
    volumes:
      - ./services:/app
    command:  
    - /bin/bash
    - -c
    - |
        python -u load_es_fixtures.py &
        mod_wsgi-express start-server --reload-on-changes ./services/wsgi.py

  frontend:
    image: tp33/django
    container_name: frontend
    networks:
      - public
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    command: bash -c "pip install whitenoise
      && pip install django-crispy-forms
      && pip install Pillow
      && mod_wsgi-express start-server --reload-on-changes ./frontend/wsgi.py"

  # frontend1:
  #   image: tp33/django
  #   container_name: frontend1
  #   networks:
  #     - public
  #   ports:
  #     - "8003:8000"
  #   volumes:
  #     - ./frontend:/app
  #   command: bash -c "pip install whitenoise
  #     && pip install django-crispy-forms
  #     && pip install Pillow
  #     && mod_wsgi-express start-server --reload-on-changes ./frontend/wsgi.py"

  # frontend2:
  #   image: tp33/django
  #   container_name: frontend2
  #   networks:
  #     - public
  #   ports:
  #     - "8005:8000"
  #   volumes:
  #     - ./frontend:/app
  #   command: bash -c "pip install whitenoise
  #     && pip install django-crispy-forms
  #     && pip install Pillow
  #     && mod_wsgi-express start-server --reload-on-changes ./frontend/wsgi.py"

  kafka:
    image: spotify/kafka
    container_name: kafka
    # logging:
    #   driver: "none"
    networks:
        - batch_network
        - service_mesh
    environment:
        ADVERTISED_HOST: kafka
        ADVERTISED_PORT: 9092
    hostname: kafka
    
  es:
    image: elasticsearch:7.4.0
    container_name: es
    # logging:
    #   driver: "none"
    environment:
        - discovery.type=single-node
    networks:
        - service_mesh
        - batch_network
    ports:
        - "9200:9200"
  
  batch:
    image: tp33/django
    container_name: batch
    # logging:
    #   driver: "none"
    networks:
        - batch_network
    depends_on: 
      - "es"
      - "kafka"
    restart: on-failure
    command: 
      - /bin/bash
      - -c
      - |
          set -m
          python -u logger.py &
          python -u count_logs.py & 
          python -u batch.py & 
          wait $$!

    volumes:
      - ./batch:/app

  # selenium-chrome:
  #   image: selenium/standalone-chrome
  #   logging:
  #     driver: "none"
  #   container_name: selenium-chrome
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   networks:
  #   - service_mesh
  #   - public
  #   ports:
  #   - "4444:4444"

  # selenium-test:
  #   image: tp33/django
  #   logging:
  #     driver: "none" 
  #   container_name: selenium-test
  #   networks:
  #   - service_mesh
  #   volumes:
  #   - ./selenium:/app

networks:
  backend:
  service_mesh:
  public:
  batch_network:
