version: "3"
services:
  models:
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - ./egg:/egg
    ports:
      - "8001:8000"
    networks:
      - backend
    command: bash -c "mod_wsgi-express start-server --working-directory /egg --reload-on-changes /egg/egg/wsgi.py"

networks:
  backend: