version: "3"
services:
  models:
    image: tp33/django
    container_name: models
    environment: 
      - TRAVIS
    external_links:
      - mysql:db
    volumes:
      - ./models:/app
    ports:
      - "8001:8000"
    networks:
      - service_mesh
      - backend
    command: bash -c "pip install whitenoise
      && pip install django-crispy-forms
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py loaddata ./fixtures/manufacturer_fixtures.json
      && python manage.py loaddata ./fixtures/product_fixtures.json
      && mod_wsgi-express start-server --reload-on-changes ./models/wsgi.py"

  services:
    image: tp33/django
    container_name: services
    networks:
      - service_mesh
      - public
    ports:
      - "8002:8000"
    volumes:
      - ./services:/app
    command:  
    - /bin/bash
    - -c
    - |
        python -u load_es_fixtures.py &
        mod_wsgi-express start-server --reload-on-changes ./services/wsgi.py

  frontend:
    image: tp33/django
    container_name: frontend
    networks:
      - public
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    command: bash -c "pip install whitenoise
      && pip install django-crispy-forms
      && mod_wsgi-express start-server --reload-on-changes ./frontend/wsgi.py"

  kafka:
    image: spotify/kafka
    container_name: kafka
    networks:
        - batch_network
        - service_mesh
    environment:
        ADVERTISED_HOST: kafka
        ADVERTISED_PORT: 9092
    hostname: kafka
    
  es:
    image: elasticsearch:7.4.0
    container_name: es
    environment:
        - discovery.type=single-node
    networks:
        - service_mesh
        - batch_network
    ports:
        - "9200:9200"
  
  batch:
    image: tp33/django
    container_name: batch
    networks:
        - batch_network
    depends_on: 
      - "es"
      - "kafka"
    restart: on-failure
    command: 
      - /bin/bash
      - -c
      - |
          set -m
          python -u logger.py &
          python -u count_logs.py & 
          python -u batch.py & 
          wait $$!

    volumes:
      - ./batch:/app
  # selenium-chrome:
  #   image: selenium/standalone-chrome
  #   container_name: selenium-chrome
  #   networks:
  #   - service_mesh
  #   - public
  #   ports:
  #   - "4444:4444"

  # selenium-test:
  #   image: tp33/django
  #   container_name: selenium-test
  #   networks:
  #   - service_mesh
  #   volumes:
  #   - ./selenium:/app
  #   command: bash -c "pip install selenium && python selenium_tests.py"
  spark-master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    container_name: spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./data:/tmp/data

  spark-worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    container_name: spark-worker
    hostname: spark-worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 512m
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./data:/tmp/data
    

networks:
  backend:
  service_mesh:
  public:
  batch_network:

