# Generated by Django 2.2.4 on 2020-02-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('man_id', models.AutoField(primary_key=True, serialize=False)),
                ('man_name', models.CharField(max_length=50)),
                ('web_url', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('man_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('warranty', models.CharField(max_length=50)),
            ],
        ),
    ]
