# Generated by Django 2.2.4 on 2020-03-01 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
