# Generated by Django 2.2.4 on 2020-03-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
