# Generated by Django 2.2.4 on 2020-03-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_product_img_url'),
        ('models_app', '0003_auto_20200301_2102'),
    ]

    operations = [
    ]
