# Generated by Django 2.2.4 on 2020-03-02 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_product_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_url',
        ),
    ]
