# Generated by Django 2.2.4 on 2020-03-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_merge_20200302_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
