# Generated by Django 2.2.4 on 2020-03-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_auto_20200303_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_man',
            field=models.BooleanField(default=False),
        ),
    ]
