# Generated by Django 2.2.4 on 2020-03-22 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_user_is_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_man',
        ),
    ]
