# Generated by Django 2.2.4 on 2020-03-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0008_remove_user_is_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='man_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
