# Generated by Django 2.2.4 on 2020-03-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0009_auto_20200323_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='phone_num',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='password',
            field=models.CharField(default='weakPass', max_length=50),
            preserve_default=False,
        ),
    ]
