# Generated by Django 2.2.4 on 2020-03-23 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0008_authenticator'),
        ('models_app', '0010_auto_20200323_0158'),
    ]

    operations = [
    ]
