# Generated by Django 2.2.4 on 2020-03-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0011_merge_20200323_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
