# Generated by Django 2.2.4 on 2020-03-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0012_auto_20200324_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticator',
            old_name='user_id',
            new_name='auth_id',
        ),
    ]
