# Generated by Django 2.2.4 on 2020-04-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0013_auto_20200324_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='email',
            field=models.CharField(default='default@email.com', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
