# Generated by Django 2.2.4 on 2020-04-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0014_manufacturer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticator',
            name='auth_model',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
