# Generated by Django 2.2.4 on 2020-05-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0015_authenticator_auth_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.FileField(default=None, upload_to='testing/'),
            preserve_default=False,
        ),
    ]
