# Generated by Django 2.2.4 on 2020-05-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0017_auto_20200507_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
