# Generated by Django 2.2.4 on 2020-05-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0018_auto_20200507_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_items', models.CharField(max_length=1000)),
            ],
        ),
    ]
