# Generated by Django 2.1.4 on 2020-02-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='man_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
