# Generated by Django 2.2.4 on 2020-02-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200205_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warrenty',
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
