# Generated by Django 2.2.4 on 2020-02-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200206_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='man_id',
            field=models.IntegerField(),
        ),
    ]
