# Generated by Django 2.1.4 on 2020-02-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200205_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='name',
            new_name='man_name',
        ),
    ]
